# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jean-François Labbé
email:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter: '@jeffff35'
github:  jean-francois-labbe
linkedin: jeanfrancoislabbe
phone: 06 66 88 02 08
website: jean-francois-labbe.com
tagline: Full Stack Developer
pic: profile.png

# Build settings
markdown: kramdown
theme: minima
plugins_dir:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
